services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env_file:
      - config.env
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    depends_on:
      - unbound
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "google.com"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - ./unbound/root.hints:/opt/unbound/etc/unbound/root.hints
      - ./unbound/update-root-hints.sh:/opt/unbound/update-root-hints.sh
    command: ["/opt/unbound/update-root-hints.sh"]
    restart: unless-stopped
