server:
  verbosity: 1
  interface: 0.0.0.0
  port: 53
  do-ip4: yes
  do-udp: yes
  do-tcp: yes
  root-hints: "var/lib/unbound/root.hints"
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: no
  prefetch: yes
  prefetch-key: yes
  num-threads: 2
  so-rcvbuf: 4m
  so-sndbuf: 4m
  msg-cache-size: 50m
  rrset-cache-size: 100m
  cache-min-ttl: 3600
  cache-max-ttl: 86400

forward_zone:
  name: "."
  forward-addr: 127.0.0.1@53
